### ISSUE TITLE
Duplicate ModalForm

### ISSUE THREAD

**Issue by packbier** [dktapps-pm-pl/pmforms#3]
If I send a player a modal form it will send it "doubled"

If I have a more then 6 lines and the player will scroll down it will look like this:
https://prnt.sc/sbl873

**Comment by dktapps** [comment]
That looks like a client sided bug to me. There's no complex logic in pmforms that would cause this behaviour unless it happens to other implementations too.

**Comment by packbier** [comment]
For some reason it is now working again.
