### ISSUE TITLE
Can you make an example for server setting form?

### ISSUE THREAD

**Issue by Endermanbugzjfc** [dktapps-pm-pl/pmforms#4]
Idk how to register a server setting for a player, I tried to combine it with the Custom Setting plugin but it didn't work (Nothing changed in the setting section). So can you **please make an example or demo of the server setting form**? Here is the code that I tried

`
 public function onDataPacket(DataPacketReceiveEvent $event) {
                
                $custs = (new ServerSettingsForm("Personal Settings", [new Dropdown("dropdown_gender", "Gender: ", ["Male", "Female", 0]), new Toggle("toggle_muteChat", "Mute chat: ", false)], new FormIcon("https://gamepedia.cursecdn.com/minecraft_zh_gamepedia/e/e7/Lit_Redstone_Lamp_JE3_BE2.png?version=4a1c6b0943c08b2f35300010ce90946f", "url"), function(Player $player, CustomFormResponse $data) : void {print_r($data))}));
                 
		$packet = $event->getPacket();
		if($packet instanceof ServerSettingsRequestPacket) {
			$packet = new ServerSettingsResponsePacket();
			$packet->formData = $custs;
			$packet->formId = 5928;
			$event->getPlayer()->dataPacket($packet);
		} elseif($packet instanceof ModalFormResponsePacket) {
			$formId = $packet->formId;
			if($formId !== 5928) {
				return;
			}
		}
	}
`

**Comment by dktapps** [comment]
This library doesn't deal with server settings form.
